# Generated by Django 3.2.8 on 2021-12-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaptopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laptop',
            new_name='Laptop1',
        ),
    ]
